service: caring-fred

provider:
  name: aws
  region: ${env:AWS_DEFAULT_REGION, 'ca-central-1'}
  stage: ${opt:stage}
  stackName: ${self:service}-dynamo-${self:provider.stage}
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: ${self:service}-${self:provider.stage}-serverlessdeploymentbucket
    serverSideEncryption: AES256

  # Force serverless variables to be double braced - ${{ }} - so as to
  # not interfere with Fn::Sub
  # See https://serverless.com/framework/docs/providers/aws/guide/variables/#using-custom-variable-syntax
  # variableSyntax: "\\${{([ ~:a-zA-Z0-9._@\\'\",\\-\\/\\(\\)]+?)}}"

resources:
  Resources:
    TableUser:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:service}-${self:provider.stage}-user
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: email
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        GlobalSecondaryIndexes:
        - IndexName: user-email-index
          KeySchema:
          - AttributeName: email
            KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        SSESpecification:
          SSEEnabled: True
        BillingMode: PAY_PER_REQUEST

    TableOrganizations:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:service}-${self:provider.stage}-organization
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: search_name
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        GlobalSecondaryIndexes:
        - IndexName: search_name-index
          KeySchema:
          - AttributeName: search_name
            KeyType: HASH
          Projection:
            ProjectionType: KEYS_ONLY
        SSESpecification:
          SSEEnabled: True
        BillingMode: PAY_PER_REQUEST

    TableEvents:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Delete
      Properties:
        TableName: ${self:service}-${self:provider.stage}-event
        AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: owner
          AttributeType: S
        KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: owner
          KeyType: RANGE
        SSESpecification:
          SSEEnabled: True
        BillingMode: PAY_PER_REQUEST


  #===================================================================
  # Stack Outputs
  #===================================================================
  Outputs:
    ServerlessDeploymentBucketName:
      Value:
        Fn::Join:
          - ''
          - - ${self:service}-${self:provider.stage}-serverlessdeploymentbucket
      Export:
        Name: !Sub sls-${self:service}-dynamo-${self:provider.stage}-ServerlessDeploymentBucketName
